### ISSUE TITLE
Add module to opm

### ISSUE THREAD

**Issue by amingilani** [openresty/replace-filter-nginx-module#22]
Since I'm basing my openresty off of the original docker installation, it would be so much better if you could just turn this into an `opm` package.

**Comment by agentzh** [comment]
@amingilani opm only supports Lua modules right now though there's plans to add support for nginx C modules in the future.

**Comment by amingilani** [comment]
I see, thanks for clarifying. So there's basically no way to install this without recompiling nginx/openresty?

**Comment by amingilani** [comment]
Forgive my ignorance, I'm new to the whole nginx scripting world :)
