### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by deepesh-agarwal** [openresty/replace-filter-nginx-module#6]
I am getting this error while trying to compile latest Nginx with this module : 

``````
/home/ec2-user/replace-filter-nginx-module/src/ngx_http_replace_script.c: In function ângx_http_replace_script_copy_capture_codeâ:
/home/ec2-user/replace-filter-nginx-module/src/ngx_http_replace_script.c:466:47: error: variable âposâ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_http_replace_script.o] Error 1
make[1]: Leaving directory `/home/ec2-user/nginx-1.5.1'
make: *** [build] Error 2```
``````

**Comment by mtx-z** [comment]
Hello, i have the same probleme. 
The --with-ld-opt="-Wl,-rpath,/usr/local/lib" has been used in configure. 
I tried the "LD_LIBRARY_PATH=/usr/local/lib" before starting nginx but still same...

```
root@server:~# locate libsregex.so.0
/installers/sregex/sregex/libsregex.so.0
/usr/local/lib/libsregex.so.0
/usr/local/lib/libsregex.so.0.0.1
```

Anything i missed ? Thanks.

**Comment by agentzh** [comment]
@mtx-z Please do not reply to a closed issue. Better create a new one. Thank you. Also, please provide as much details as possible when you report a problem. Simply saying "the same problem" is not helpful at all. Who knows what part of the original problem you are sharing on your side? Not to mention the original reporter of this issue has already resolved his problems.
